import json



#### 크롤링 잘못된것 수동 조정

# # 저장된 챕터 JSON 불러오기
# with open("NAPD_frag.json", "r", encoding="utf-8") as f:
#     napd = json.load(f)

# List_illustrations = """LOENTSCHENTAL VALLEY IN SWITZERLAND
# HAND-MILL USED BY NATIVES IN LOENTSCHENTAL VALLEY
# NATIVES OF MODERN SWISS VALLEY SHOWING NORMAL DESIGN OF FACE AND DENTAL ARCHES WHEN ADEQUATE NUTRITION IS PROVIDED
# NATIVES OF LOENTSCHENTAL VALLEY SHOWING TOOTH DECAY AND DEFORMED DENTAL ARCHES TYPICAL OF THOSE LIVING ON MODERN FOODS
# A TYPICAL BLACK-HOUSE" ON THE ISLE OF LEWIS. NATIVES OF THE ISLE OF LEWIS
# TOOTH DECAY IN NATIVE OF ISLE OF HARRIS LIVING ON MODERN FOODS AND EXCELLENT TEETH OF NATIVES LIVING ON PRIMITIVE FOODS
# GAELIC CHILDREN LIVING ON NATIVE FOODS. GAELIC CHILDREN LIVING ON MODERN FOODS
# VARIATIONS IN GROWTH OF OATS FERTILIZED WITH VARYING QUANTITIES OF SMOKE-THATCH
# PRIMITIVE ALASKAN ESKIMOS SHOWING EXCELLENT FACIAL AND DENTAL ARCH FORMATION
# PRIMITIVE ALASKAN MOTHERS
# ALASKAN ESKIMOS SHOWING EFFECT ON TEETH OF MODERN FOODS
# DEFECTIVE TEETH AND DENTAL ARCHES IN ESKIMO CHILDREN LIVING ON MODERN FOODS
# DRIED EGGS OF SALMON ARE AN IMPORTANT ITEM OF NUTRITION
# FACIAL AND DENTAL ARCH DEFORMITY IN WHITE BOY BORN IN ALASKA AND LIVING ON MODERN FOODS
# FAMILY OF FOREST INDIANS OF NORTHERN CANADA
# MODERNIZED INDIAN CHILDREN WITH TUBERCULOSIS
# INDIAN WOMEN AND GIRLS TYPICAL OF THOSE LIVING ON PRIMITIVE FOODS
# INDIAN WOMEN TYPICAL OF THOSE LIVING ON MODERN FOODS
# DEFORMED FACIAL FORMATION IN CHILDREN OF FIRST GENERATION AFTER ADOPTION OF MODERN FOODS BY PARENTS
# PRIMITIVE INDIANS OF CENTRAL CANADA: PARENTS DEVELOPED ON NATIVE FOODS, CHILDREN ON MODERN FOODS
# TYPICAL CRIPPLED CHILDREN FOUND AMONG INDIANS LIVING ON MODERN FOODS
# SKULLS OF PRIMITIVE INDIANS SHOWING SUPERB DENTAL ARCHES
# SKULLS OF PRIMITIVE INDIANS SHOWING EXCELLENT BONE FORMATION
# SEMINOLE INDIANS, TYPICAL OF THOSE LIVING ON NATIVE FOODS
# DENTAL CARIES IN SEMINOLE INDIANS LIVING ON MODERN FOODS
# SEMINOLE INDIAN CHILDREN SHOWING CHANGES IN FACIAL AND DENTAL ARCH FORM WHICH RESULT FROM MODERN FOODS
# SKULLS OF PRE-COLUMBIAN INDIANS OF FLORIDA
# MELANESIANS TYPICAL OF THOSE LIVING UNDER NATIVE CONDITIONS
# FACIAL BONE FORMATION IN MELANESIANS LIVING ON NATIVE FOODS
# FIJI COUNCIL HOUSE AND HEREDITARY FIJI MONARCH
# TOOTH DECAY IN NATIVES OF FIJI ISLANDS LIVING ON IMPORTED FOOD
# TOOTH DECAY AND CHANGES IN ARCH FORMATION IN FIRST GENERATION AFTER ADOPTION OF MODERN FOODS
# PERFECT DENTAL ARCHES OF POLYNESIANS LIVING UNDER NATIVE CONDITIONS
# TAHITIANS SHOWING DENTAL CARIES DUE TO IMPORTED FOODS
# CHANGES IN TEETH AND IN DENTAL ARCH FORMATION OF POLYNESIANS LIVING ON MODERN FOODS
# SAMOANS TYPICAL OF EXCELLENT FACIAL AND DENTAL ARCH FORMATION WHEN LIVING ON NATIVE FOODS. CHILDREN WITH FORMATION TYPICAL OF THOSE BORN OF UNDER-NOURISHED PARENTS
# HAWAIIAN FAMILY SHOWING CHANGES IN FACIAL FORM IN YOUNGER CHILDREN OF SAME FAMILY
# TOOTH DECAY AND TUBERCULOSIS AS A RESULT OF UNDER-NUTRITION IN A POLYNESIAN GIRL
# MEMBERS OF MASAI TRIBE ILLUSTRATING EXCELLENT RESULTS OF DIET OF MEAT, MILK AND BLOOD
# METHOD BY WHICH BLOOD IS DRAWN FROM STEER
# FACIAL AND DENTAL ARCH DEVELOPMENT IN AFRICAN TRIBES LIVING ON NATIVE FOODS
# FACIAL AND DENTAL ARCH DEVELOPMENT IN MEMBERS OF BELGIAN CONGO TRIBE LIVING ON NATIVE FOODS
# PYGMIES OF BELGIAN CONGO
# DENTAL CARIES IN AFRICANS WHO HAVE ADOPTED MODERN FOODS
# CHANGES IN FACIAL AND DENTAL ARCH DEVELOPMENT IN CHILDREN OF FIRST GENERATION AFTER ADOPTION BY PARENTS OF MODERN FOODS
# AFRICANS SHOWING FACIAL DEFORMITIES DUE TO DIET OF MODERN FOODS
# AFRICANS SHOWING FACIAL DEFORMITIES IN FIRST GENERATION AFTER ADOPTION BY PARENTS OF MODERN FOODS
# AFRICAN CHILDREN SHOWING A MARKED DEPRESSION OF MIDDLE THIRD OF FACE DUE TO MALNUTRITION OF PARENTS
# CAMELS' MILK IS AN IMPORTANT ITEM OF NUTRITION IN ASIA AND AFRICA
# FACIAL DEFORMITIES FOUND IN BOYS AND GIRLS LIVING IN CAIRO UNDER MODERN CONDITIONS
# AFRICAN CHILDREN WALKING ON "ALL FOURS"
# TYPICAL ABORIGINES OF AUSTRALIA
# MAGNIFICENT DENTAL ARCHES AND TEETH FOUND IN ABORIGINES
# DENTAL CARIES IN ABORIGINES LIVING ON MODERN FOODS
# CHANGES IN TEETH AND ARCH FORMATION IN MODERNIZED ABORIGINES
# DISTURBANCE IN FACIAL GROWTH IN MODERNIZED ABORIGINES
# DEFORMITY PATTERNS PRODUCED IN ABORIGINES BY MODERN FOOD
# EFFECTS OF MALNUTRITION IN AUSTRALIAN ABORIGINES LIVING ON A RESERVATION
# TYPICAL ABORIGINE MOTHERS WITH THEIR CHILDREN
# COMPARISON OF SKULL OF TYPICAL ABORIGINE WITH THAT OF PEKING MAN
# INHABITANTS OF ISLANDS NORTH OF AUSTRALIA HAVE SPLENDIDLY BUILT BODIES WITH FINE FACIAL AND DENTAL ARCH FORM
# COMPARISON OF FACIAL AND DENTAL ARCH FORMATION IN NATIVE AND IN WHITE CHILDREN ON THURSDAY ISLAND
# GOOD PHYSICAL DEVELOPMENT OF NATIVES OF HAMMOND ISLAND
# DENTAL ARCHES IN NATIVES ON THE ISLANDS OF THE GREAT BARRIER REEF
# CONTRAST IN FACIAL AND DENTAL ARCH FORM BETWEEN PRIMITIVE AND MODERNIZED NATIVES
# DEFORMED DENTAL ARCHES IN WHITE CHILDREN ON THURSDAY ISLAND
# TOOTH DECAY IN WHITE CHILDREN IN TORRES STRAIT ISLANDS
# DENTAL CLINIC MAINTAINED BY NEW ZEALAND GOVERNMENT
# THE MAORI HAD THE REPUTATION OF HAVING THE FINEST TEETH AND BODIES OF ANY RACE IN THE WORLD
# TOOTH DECAY IS FOUND IN MODERNIZED MAORI
# THE WHITES LIVING IN NEW ZEALAND HAVE POOR TEETH
# FACIAL DEFORMITIES IN MAORI BORN AFTER ADOPTION OF MODERN FOODS
# MAORI SKULLS SHOWING FINE PHYSICAL DEVELOPMENT
# MAORI DEMONSTRATING SOME OF THE ACCESSORY ESSENTIALS OBTAINED FROM THE SEA
# TREPHINED SKULLS OF ANCIENT PEOPLES OF PERU
# TREPHINED SKULLS WITH GOLD PLATES IN POSITION
# POTTERY JAR DEPICTING ANCIENT PERUVIAN SURGERY. BONE SHOWING HEALING OF FRACTURE
# SKULLS OF FISHERMEN OF CHIMU CULTURE
# ANCIENT AQUEDUCT OF PERU
# DESCENDANTS OF ANCIENT CHIMUS SHOWING FLATTENING OF BACK OF HEAD
# SOME DESCENDANTS OF THE ANCIENT CHIMUS ARE STILL LIVING IN A FEW FISHING VILLAGES IN THE NORTH OF PERU
# STONE FORTRESS BUILT BY PRIMITIVE PEOPLE OF ANDEAN SIERRA
# TYPICAL SKULLS OF HIGH SIERRA INDIANS
# DESCENDANTS OF THE TAUHUANOCAN INDIANS OF PERU
# THE QUICHUA INDIANS LIVING IN THE HIGH ANDES ARE DESCENDANTS OF THE INCAS
# INDIANS OF THE HIGH ANDES HAVE MAGNIFICENT PHYSIQUES
# INDIANS OF THE HIGH ANDES HAVE SUPERB FACIAL AND DENTAL ARCH DEVELOPMENT
# INTRODUCTION OF MODERN FOODS TO SIERRA INDIANS PRODUCED WRECKAGE OF PHYSIQUES
# JUNGLE INDIANS OF THE AMAZON BASIN
# FACIAL AND DENTAL ARCH DEVELOPMENT OF THE JUNGLE INDIANS IS SUPERB
# EXCELLENCE OF SKELETAL DEVELOPMENT OF JUNGLE INDIANS AS EXPRESSED IN FACES AND DENTAL ARCHES
# A MARKED CHANGE IN FACIAL FORM WITH CROWDING OF TEETH OCCURS IN JUNGLE INDIANS BORN AFTER ADOPTION OF MODERN FOODS
# RAPID HEALING OF FRACTURED FEMUR IN BOY SUFFERING FROM MALNUTRITION, AFTER INSTITUTION OF PROPER NUTRITION
# IMPROVEMENT ACCOMPLISHED BY PROPER NUTRITION IN BOY SUFFERING FROM INFLAMMATORY RHEUMATISM
# EFFECT OF DIFFERENT WHEAT PRODUCTS ON RATS
# TEETH SHOWING PERMEABILITY OF DECAYED DENTIN TO SILVER NITRATE
# THREE CASES ILLUSTRATING HOW NATURE CAN CLOSE AN EXPOSURE OF PULP DUE TO DENTAL CARIES
# FOUR MELANESIANS BORN ON FOUR DIFFERENT ISLANDS LOOK LIKE BROTHERS BUT ARE NOT BLOOD RELATIONS
# FOUR POLYNESIAN GIRLS LIVING ON DIFFERENT ISLANDS ARE NOT RELATED THOUGH THEY LOOK LIKE SISTERS
# DISTURBED HEREDITY: TWO PERUVIAN INDIAN FATHERS WITH GOOD PHYSICAL DEVELOPMENT AND THEIR SONS WHO SHOW DEFECTS
# DISTURBED HEREDITY ILLUSTRATED BY FATHER AND SON OF WAKAMBA TRIBE OF CENTRAL AFRICA
# DISTURBED HEREDITY IN QUICHA INDIANS
# DISTURBED HEREDITY IN AUSTRALIAN ABORIGINES
# TWO MAORI SISTERS, AND TWO WHITE SISTERS IN PERU, SHOWING FACIAL CHANGES THAT MAY OCCUR IN SAME GENERATION WITH CHANGE FROM PRIMITIVE TO MODERN DIET BY PARENTS
# SIX BROTHERS SHOWING FACIAL CHANGES IN SAME GENERATION DUE TO CHANGE FROM PRIMITIVE TO MODERN FOODS BY PARENTS
# CHANGE IN FACIAL FORM IN TWO YOUNGER BROTHERS, CORRESPONDING TO CHANGE IN DIET BY PARENTS
# NATIVES FROM ISLANDS NORTH OF AUSTRALIA SHOWING PROGRESSIVE FACIAL CHANGE IN SAME FAMILY DUE TO CHANGE IN FOODS
# WHITE GIRLS IN NEW ZEALAND ILLUSTRATE PROGRESSIVE LENGTHENING AND NARROWING OF FACE AND HIPS
# NEW ZEALAND MAORI ILLUSTRATING PROGRESSIVE CHANGE IN FACIAL FORM OF TWO YOUNGER BOYS
# NEW ZEALAND MAORI ILLUSTRATING MARKED UNDERSIZE AND DEFORMITY OF FEET IN SECOND CHILD IN FAMILY
# MODERNIZED PERUVIAN INDIAN BOY SHOWING DISTURBED DEVELOPMENT OF FACE AND FOOT
# MODERNIZED COASTAL INDIAN OF ECUADOR SHOWING SERIOUS PHYSICAL DEFORMITIES
# ESKIMO CHILDREN ILL IN TUBERCULOSIS WARD OF THE GOVERNMENT HOSPITAL AT JUNEAU
# PATIENTS IN THE MAORI HOSPITAL IN NEW ZEALAND SHOWING MARKED FACIAL UNDER-DEVELOPMENT
# GIRLS IN TUBERCULOSIS WARD OF NEW ZEALAND HOSPITAL FOR MAORI SHOW MARKED FACIAL AND DENTAL ARCH DISTURBANCES
# NATIVE HAWAIIAN CHILDREN WITH TUBERCULOSIS, SHOWING MARKED DISTURBANCES OF FACIAL FORM AND DENTAL ARCH DEVELOPMENT
# DEFORMITIES OF PIG DUE TO LACK OF VITAMIN A IN MOTHERS DIET
# DEFORMITIES DUE TO LACK OF ADEQUATE VITAMIN A IN MOTHERS DIET
# MANY YOUNG OF MODERN DOMESTIC ANIMALS ARE BORN WITH DEFORMITIES
# PUPPIES BORN WITH PHYSICAL DEFECTS DUE TO DEFICIENCY OF VITAMIN A IN FATHER
# TYPICAL DEFORMITIES IN DOMESTIC ANIMALS
# CRIMINALS. WERE THEIR UNSOCIAL TRAITS RELATED TO INCOMPLETE BRAIN ORGANIZATION ASSOCIATED WITH PRENATAL INJURY
# MARKED LACK OF NORMAL FACIAL DEVELOPMENT IN NOTORIOUS YOUNG CRIMINALS
# TYPICAL MONGOLOID DEFECTIVE
# PHYSICAL CHANGES IN MONGOLOID TYPE DUE TO MOVEMENT OF MAXILLARY BONES TO STIMULATE PITUITARY GLAND IN BASE OF BRAIN
# X-RAY PICTURES SHOWING POSITION OF TEETH BEFORE AND DURING OPERATION TO MOVE MAXILLARY BONES
# TWIN BOYS WITH SAME DEFORMITY OF DENTAL ARCH
# BOYS TYPICAL OF GROUP IN SPECIAL SCHOOL FOR BACKWARD CHILDREN
# FIJI WOMAN WHO HAS GONE LONG DISTANCE TO GATHER SPECIAL FOOD NEEDED FOR PRODUCTION OF HEALTHY CHILDREN
# AFRICAN WOMAN WHO HAS COME DOWN THE MOUNTAINS TO GATHER SPECIAL PLANTS OF WHICH THE ASHES PREVENT GOITER
# X-RAYS OF TEETH OF THREE CHILDREN IN ONE FAMILY SHOW PROGRESSIVE INJURY IN YOUNGER CHILDREN
# X-RAYS ILLUSTRATING PROGRESSIVE INJURY IN TWO YOUNGER CHILDREN IN FAMILY
# X-RAYS COMPARING DEFORMITIES OF FACIAL FORM IN CHILD BORN AFTER LONG LABOR WITH BETTER FACIAL FORM IN SISTER BORN AFTER SHORT LABOR
# GIRL SHOWING RELATIONSHIP BETWEEN LACK OF PELVIC DEVELOPMENT AND DEFORMITY OF FACE
# """

# li = List_illustrations.split("\n")
# print(len(li)) # 134

# for i, para in enumerate(napd):
#     if para["type"]!="text":
#         continue
#     if para["para_id"]=="0008":
#         para["text"] = """I. 	 Why Seek Wisdom from Primitive Races
# II. 	 The Progressive Decline of Modern Civilization
# III.	 Isolated and Modernized Swiss
# IV.	 Isolated and Modernized Gaelics
# V.	 Isolated and Modernized Eskimos
# VI.	 Primitive and Modernized North American Indians
# VII.	 Isolated and Modernized Melanesians
# VIII.	 Isolated and Modernized Polynesians
# IX.	 Isolated and Modernized African Tribes
# X.	 Isolated and Modernized Australian Aborigines
# XI.	 Isolated and Modernized Torres Strait Islanders
# XII.	 Isolated and Modernized New Zealand Maori
# XIII.	 Ancient Civilizations of Peru
# XIV. 	 Isolated and Modernized Peruvian Indians
# XV.	 Characteristics of Primitive and Modernized Dietaries
# XVI.	 Primitive Control of Dental Caries
# XVII.	 One Origin of Physical Deformities
# XVIII.	 Prenatal Nutritional Deformities and Disease Types
# XIX.	 Physical, Mental and Moral Deterioration
# XX.	 Soil Depletion and Plant and Animal Deterioration
# XXI.	 Practical Applications of Primitive Wisdom"""
#         #print(para["text"])


#     if para["para_id"]=="0010":
#         for i in range(len(li)-1):
#             para["text"] = para["text"] + "\n" + str(i+1) + "." + li[i]

#     if para["para_id"]=="0006":
#         para["text"] = """TO THAT KINDRED SOUL

# My Wife

# who has assisted me so greatly
# on these difficult expeditions,
# this book is lovingly dedicated."""

# with open("NAPD_frag_fixed.json", "w", encoding="utf-8") as f:
#     json.dump(napd, f, indent=2, ensure_ascii=False)




#----------

# 저장된 챕터 JSON 불러오기
with open("NAPD_frag_fixed.json", "r", encoding="utf-8") as f:
    napd = json.load(f)


for i, para in enumerate(napd):

    if para["type"] != "text":
        continue
    if len(para["text"]) > 5000: 
        #0011번 문단 글자수 10288. 나머지는 거의 10문장 이하.
        print(i)
        print(len(para["text"]))
        #split = para["text"].split("\n") #11248???
        #print(len(split)) #split by space: 133293
        #print(para["text"][40000:41000]) 

        # query = "GIRL SHOWING RELATIONSHIP"

        # index = para["text"].find(query)
        # print(index)

        # print(para["text"][index-100:index+100]) # 100글자 전후로 출력

        # print('')
